resolver: nightly-2021-07-09
packages:
- .
extra-deps:
- compact-0.2.0.0
- polysemy-1.6.0.0
- polysemy-extra-0.1.7.0
- polysemy-plugin-0.4.0.0
- git: https://github.com/polysemy-research/polysemy-zoo
  commit: 1eed0f83f595cb7f666fc238da041080ea284938

allow-newer: true
